### ISSUE TITLE
Theme Suggestion

### ISSUE THREAD

**Issue by moratoriumfinserv** [ultimatemediaorg/goum.cf-pages#5]
Theme Name: NAME YOUR THEME

CSS:
```css
:root {
    --body-bg: #090c08;
    --box-bg: #1d1e2c;
    --text: #ffffff;
    --link-accent: #dd614a;
    --link-text: #ffffff;
    --box-border-radius: 2px;
}
```
